version: '3.9'
services:
  backend:
    build: /
    image: tcc/backend
    container_name: tcc-backend
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    ports:
      - "4200:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"